name: Deploy Storybook to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupère le code de votre dépôt
      - name: Check out repository
        uses: actions/checkout@v3

      # 2. Installe la version de Node.js souhaitée
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16  # ou la version que vous utilisez

      # 3. Installe vos dépendances
      - name: Install dependencies
        run: npm ci

      # 4. Build votre Storybook
      - name: Build Storybook
        run: npm run build-storybook

      # 5. Déploie le contenu du dossier `storybook-static` sur la branche gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
          publish_branch: gh-pages
